services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "1000:1000:0755:/tmp/certs"
    volumes:
      - "./certs:/tmp/certs"
    network_mode: none

  cert-gen:
    image: docker.kurrent.com/kurrent-utils/es-gencert-cli:latest
    entrypoint: bash
    user: "1000:1000"
    command: >
      -c "mkdir -p ./certs && cd /certs
      && es-gencert-cli create-ca
      && es-gencert-cli create-node -out ./node1 -ip-addresses 127.0.0.1,172.30.240.11 -dns-names localhost
      && es-gencert-cli create-node -out ./node2 -ip-addresses 127.0.0.1,172.30.240.12 -dns-names localhost
      && es-gencert-cli create-node -out ./node3 -ip-addresses 127.0.0.1,172.30.240.13 -dns-names localhost
      && find . -type f -print0 | xargs -0 chmod 666"
    volumes:
      - "./certs:/certs"
    depends_on:
      - volumes-provisioner

  esdb-node1: &template
    image: docker.kurrent.com/${KURRENT_DOCKER_REPO:-kurrent-ce}/${KURRENT_DOCKER_CONTAINER:-kurrentdb-ce}:${KURRENT_DOCKER_CONTAINER_VERSION:-latest}
    env_file:
      - vars.env
    environment:
      - KURRENT_GOSSIP_SEED=172.30.240.12:2113,172.30.240.13:2113
      - KURRENT_INT_IP=172.30.240.11
      - KURRENT_CERTIFICATE_FILE=/etc/kurrent/certs/node1/node.crt
      - KURRENT_CERTIFICATE_PRIVATE_KEY_FILE=/etc/kurrent/certs/node1/node.key
      - KURRENT_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2111
    ports:
      - 2111:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.11
    volumes:
      - ./certs:/etc/kurrent/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

  esdb-node2:
    <<: *template
    environment:
      - KURRENT_GOSSIP_SEED=172.30.240.11:2113,172.30.240.13:2113
      - KURRENT_INT_IP=172.30.240.12
      - KURRENT_CERTIFICATE_FILE=/etc/kurrent/certs/node2/node.crt
      - KURRENT_CERTIFICATE_PRIVATE_KEY_FILE=/etc/kurrent/certs/node2/node.key
      - KURRENT_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2112
    ports:
      - 2112:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.12

  esdb-node3:
    <<: *template
    environment:
      - KURRENT_GOSSIP_SEED=172.30.240.11:2113,172.30.240.12:2113
      - KURRENT_INT_IP=172.30.240.13
      - KURRENT_CERTIFICATE_FILE=/etc/kurrent/certs/node3/node.crt
      - KURRENT_CERTIFICATE_PRIVATE_KEY_FILE=/etc/kurrent/certs/node3/node.key
      - KURRENT_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
    ports:
      - 2113:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.13

networks:
  clusternetwork:
    name: kurrentdb.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.240.0/24