name: Get Kurrent Docker repo
on:
  workflow_call:
    inputs:
      runtime_env:
        description: The runtime environment we want to run like release or staging
        type: string
        default: release

    outputs:
      docker_repo:
        description: Kurrent docker repository
        value: ${{ jobs.provide_docker.outputs.docker_repo }}

      docker_container:
        description: Kurrent docker container
        value: ${{ jobs.provide_docker.outputs.docker_container }}

jobs:
  provide_docker:
    runs-on: ubuntu-latest
    outputs:
      docker_repo: ${{ steps.set_docker.outputs.docker_repo }}
      docker_container: ${{ steps.set_docker.outputs.docker_container }}
    steps:
      - name: Set Kurrent docker repo
        id: set_docker
        run: |
          case ${{ inputs.runtime_env }} in
            "release")
              echo "docker_repo=kurrent-ce" >> $GITHUB_OUTPUT
              echo "docker_container=kurrentdb-ce" >> $GITHUB_OUTPUT
            ;;

            "staging")
              echo "docker_repo=kurrent-staging-ce" >> $GITHUB_OUTPUT
              echo "docker_container=kurrentdb-oss" >> $GITHUB_OUTPUT
            ;;
          
            "enterprise")
              echo "docker_repo=kurrent-ee" >> $GITHUB_OUTPUT
              echo "docker_container=kurrentdb-commercial" >> $GITHUB_OUTPUT
            ;;

            *)
              echo "docker_repo=kurrent-ce" >> $GITHUB_OUTPUT
              echo "docker_container=kurrentdb-ce" >> $GITHUB_OUTPUT
            ;;
          esac