name: Pull Request check
on:
  pull_request:
    paths-ignore:
      - "tests/**"
      - "examples/**"
      - "**.md"
    types: [opened, edited]
jobs:
  checkPullRequest:
    name: Pull Request check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pull requests
        uses: EventStore/Automations/pr-check@master