name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-11]
        rust: [stable, beta, nightly]
        exclude:
          - os: windows-2019
            rust: beta

          - os: windows-2019
            rust: nightly

          - os: macos-11
            rust: beta

          - os: macos-11
            rust: nightly


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        rustup update
        rustup default ${{ matrix.rust }}

    - name: Build
      run: cargo check --all-targets
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: Unit tests
      run: cargo test --lib

  tests:
    needs: build
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        version: [previous-lts, lts, latest, ci]

    uses: ./.github/workflows/tests.yml
    with:
      esdb_version: ${{ matrix.version }}

  linting:
    name: Linting
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        rustup update stable
        rustup component add clippy
        rustup component add rustfmt
    - name: Linting
      run: cargo clippy --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt -- --check
