name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo check
      continue-on-error: ${{ matrix.rust == 'nightly' }}
  tests:
    name: Tests on 20.6.1 (gRPC)
    needs: build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        docker-compose up -d
        RUST_BACKTRACE='1' RUST_LOG='integration=debug,eventstore=debug' cargo test --no-fail-fast
        docker-compose down

  linting:
    name: Linting
    needs: tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        rustup update
        rustup component add clippy-preview
        rustup component add rustfmt
    - name: Linting
      run: cargo clippy --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt -- --check
