name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo check --all-features
      continue-on-error: ${{ matrix.rust == 'nightly' }}
  tests:
    name: Tests on ES Version 5 (TCP)
    needs: build
    runs-on: ubuntu-18.04
    services:
      eventstore:
        image: eventstore/eventstore:release-5.0.8
        env:
          EVENTSTORE_DEV: true
        ports:
          - 1113:1113
          - 2113:2113
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: RUST_BACKTRACE='1' RUST_LOG='eventstore=debug' cargo test

  tests-next:
    name: Tests on 20.6.1 (gRPC)
    needs: tests
    runs-on: ubuntu-18.04
    services:
      eventstore:
        image: eventstore/eventstore:20.6.1-bionic
        env:
          EVENTSTORE_INSECURE: true
          EVENTSTORE_MEMDB: true
        ports:
          - 2113:2113
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cargo test --package eventstore --lib es6::grpc_connection::test_connection_string --all-features -- --exact
          RUST_BACKTRACE='1' RUST_LOG='integration=debug' cargo test --all-features es6::es6_20_6_test -- --exact --ignored

  linting:
    name: Linting
    needs: tests-next
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        rustup update
        rustup component add clippy-preview
        rustup component add rustfmt
    - name: Linting
      run: cargo clippy --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt -- --check
