name: Rust

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: rust:1.41

    services:
      eventstore:
        image: eventstore/eventstore:latest
        env:
          EVENTSTORE_DEV: true
        ports:
          - 1113/tcp
          - 2113/tcp

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        rustup component add clippy-preview
        rustup component add rustfmt
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: EVENTSTORE_HOST=eventstore RUST_BACKTRACE='1' RUST_LOG='eventstore=debug' cargo test --all-features
    - name: Linting
      run: cargo clippy --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt -- --check
