name: "Dispatch"

on:
  workflow_dispatch:
    inputs:
      runtime_env:
        description: The runtime environment. release, staging or enterprise
        type: string
        default: release

      version:
        description: "Version tag"
        required: true
        type: string

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      esdb_version: ${{ inputs.version }}
      runtime_env: ${{ inputs.runtime_env }}
    secrets: inherit