name: tests workflow

on:
  workflow_call:
    inputs:
      runtime_env:
        type: string
        default: release

      esdb_version:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  provide_docker:
    uses: ./.github/workflows/docker-repo.yml
    with:
      runtime_env: ${{ inputs.runtime_env }}

  single_node:
    needs: provide_docker
    name: Single node

    strategy:
      fail-fast: false
      matrix:
        test: [streams, projections, persistent_subscriptions, discover_error, auto_resub_on_connection_drop]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: rustup update stable

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true

      - name: Run test
        run: cargo nextest run --hide-progress-bar single_node_${{ matrix.test }}
        continue-on-error: ${{ matrix.test == 'auto_resub_on_connection_drop' }}
        env:
          ESDB_DOCKER_REGISTRY: ${{ needs.provide_docker.outputs.docker_registry }}
          ESDB_DOCKER_REPO: ${{ needs.provide_docker.outputs.docker_repo }}
          ESDB_DOCKER_CONTAINER: ${{ needs.provide_docker.outputs.docker_container }}
          ESDB_DOCKER_CONTAINER_VERSION: ${{ inputs.esdb_version }}

      - uses: actions/upload-artifact@v3
        if: failure() && matrix.test != 'auto_resub_on_connection_drop'
        with:
          name: esdb-logs
          path: eventstore/esdb_logs

  secure:
    needs: provide_docker
    name: Secure

    strategy:
      fail-fast: false
      matrix:
        test: [operations]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: rustup update stable

      - name: Generate certificates
        run: docker compose --file configure-tls-for-tests.yml up

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true

      - name: Run test
        run: cargo nextest run --hide-progress-bar single_node_${{ matrix.test }}
        env:
          ESDB_DOCKER_REGISTRY: ${{ needs.provide_docker.outputs.docker_registry }}
          ESDB_DOCKER_REPO: ${{ needs.provide_docker.outputs.docker_repo }}
          ESDB_DOCKER_CONTAINER: ${{ needs.provide_docker.outputs.docker_container }}
          ESDB_DOCKER_CONTAINER_VERSION: ${{ inputs.esdb_version }}
          SECURE: true

  cluster:
    needs: provide_docker
    name: Cluster

    strategy:
      fail-fast: false
      matrix:
        test: [streams, projections, persistent_subscriptions]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: rustup update stable

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true

      - name: Set up cluster with Docker Compose
        run: docker compose up -d
        env:
          ESDB_DOCKER_REGISTRY: ${{ needs.provide_docker.outputs.docker_registry }}
          ESDB_DOCKER_REPO: ${{ needs.provide_docker.outputs.docker_repo }}
          ESDB_DOCKER_CONTAINER: ${{ needs.provide_docker.outputs.docker_container }}
          ESDB_DOCKER_CONTAINER_VERSION: ${{ inputs.esdb_version }}

      - name: Run test
        run: cargo nextest run --hide-progress-bar cluster_${{ matrix.test }}
        env:
          ESDB_DOCKER_CONTAINER_VERSION: ${{ inputs.esdb_version }}

      - name: Shutdown cluster
        run: docker compose down

  plugins:
    needs: provide_docker
    name: plugins

    strategy:
      fail-fast: false
      matrix:
        plugin:
          - name: usercertificates
          - setup: |
              docker compose --file configure-user-certs-for-tests.yml up

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: rustup update stable

      - name: Generate certificates
        run: docker compose --file configure-tls-for-tests.yml up

      - name: Run plugin ${{ matrix.plugin.name }} setup
        run: ${{ matrix.plugin.setup }}

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true

      - name: Set the plugins environment variables
        run: |
          export eventstore__${{ matrix.plugin.name }}__enabled=true >> $GITHUB_ENV

      - name: Run test
        run: cargo nextest run --hide-progress-bar plugins_${{ matrix.plugin.name }}
        env:
          ESDB_DOCKER_REGISTRY: ${{ needs.provide_docker.outputs.docker_registry }}
          ESDB_DOCKER_REPO: ${{ needs.provide_docker.outputs.docker_repo }}
          ESDB_DOCKER_CONTAINER: ${{ needs.provide_docker.outputs.docker_container }}
          ESDB_DOCKER_CONTAINER_VERSION: ${{ inputs.esdb_version }}
          EVENTSTORE__LICENSING__LICENSEKEY: ${{ secrets.LICENSE }}
